spring:
  datasource:
    url: jdbc:mysql://%s:3306/%s?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  context-path: /gloom
  port: 8888
logging:
  config: classpath:log/logback-spring.xml
  path: C:/gloomLog
